### PR TITLE
add basic frontend sample using the goerli deployment

### LINKED ISSUE #16: After SC is complete, create a dev page with the needed web3 interactions

### PR DESCRIPTION
**Pull request by perionjames**
Closes #16 

This PR adds a simple web interface that includes:

- The contract object with ethers
- Key points of data that we need on the frontend from the smart contract
- User interacts with the contract i.e. `claim rewards`, `deposit`, `withdraw`, `extend lock` and `top up`
- Fills interactions with sample parameters
- Distribute rewards button (this would only be used by the treasury in practice)

### CODE REVIEW

**Comment by gaston-perion** [comment]
Hi @perionjames, I'm sorry but I'm not 100% sure what this repo and PR is about. Could you please provide some details? 🙏

**Review by geoshak — APPROVED** [review]
I see we have a lot of files on the repo root already.
Ideally we should move this to a subfolder, maybe named like `sample-ui` or something.

**Comment by geoshak** [comment]
Or even move it to a subfolder within the `test` directory.

**Comment by perionjames** [comment]
> Hi @perionjames, I'm sorry but I'm not 100% sure what this repo and PR is about. Could you please provide some details? 🙏

@gaston-perion this repo holds the smart contracts for staking. We talked on the phone about creating a simple dev page with the web3 integrations in it. We went over the figma design on the phone previously.

**Comment by gaston-perion** [comment]
@perionjames thanks mate. Totally, it's just I have't seen anything related with staking in the title nor description that's why I was confused

**Comment by perionjames** [comment]
@gaston-perion for price data on PERC, you can use: https://www.coingecko.com/en/api/documentation

**Pull request merged**
